# https://docs.travis-ci.com/user/docker/

dist: bionic

services:
  - docker

env:
  global:
    - ARCH=arm
    - CROSS_COMPILE=arm-linux-gnueabi-

before_install:
  - docker pull zepan/licheepi

script:
  # - travis_wait 30 docker run --rm -t -v $PWD/docker-share:/docker-share zepan/licheepi sh docker-share/boot/build.sh
  - travis_wait 60 docker run --rm -t -v $PWD/docker-share:/docker-share zepan/licheepi sh docker-share/zImage/build.sh
  # - travis_wait 120 docker run --rm -t -v $PWD/docker-share:/docker-share zepan/licheepi sh docker-share/rootfs/build.sh

jobs:
  include:
    - stage: build
        - script: travis_wait 30 docker run --rm -t -v $PWD/docker-share:/docker-share zepan/licheepi sh docker-share/boot/build.sh
        # - script: travis_wait 60 docker run --rm -t -v $PWD/docker-share:/docker-share zepan/licheepi sh docker-share/zImage/build.sh
        # - script: travis_wait 120 docker run --rm -t -v $PWD/docker-share:/docker-share zepan/licheepi sh docker-share/rootfs/build.sh
